name: Workflow with Events

on:
  push:
    branches:
      - main
      - feature/*        # e.g., feature/hello or feature/hello-world
      - feature/**       # e.g., feature/hello/world
    paths:
      - "temp.md"

jobs:
  first-job:
    runs-on: ubuntu-latest

    steps:
      - name: step one
        run: echo "step one"